# Generated by Django 4.2.14 on 2024-07-31 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_name', models.CharField(max_length=300, verbose_name='Название раздела')),
                ('ic_url', models.CharField(max_length=300, verbose_name='Название раздела в url (желательно на EU)')),
            ],
            options={
                'verbose_name': 'Раздел на сайте',
                'verbose_name_plural': 'Раздела на сайте',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=300, verbose_name='Название материала (например спрайт, анимаци ходьбы, звук)')),
                ('m_date_add', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('m_file', models.FileField(upload_to='materials/', verbose_name='Файл материала к статье')),
            ],
            options={
                'verbose_name': 'Материал к статье на сайте',
                'verbose_name_plural': 'Материалы к статье на сайте',
            },
        ),
        migrations.CreateModel(
            name='InfoSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_name', models.CharField(max_length=300, verbose_name='Название подраздела')),
                ('iss_url', models.CharField(max_length=300, verbose_name='Название подраздела в url (желательно на EU)')),
                ('iss_description', models.TextField(blank=True, verbose_name='Краткое опсание подраздела')),
                ('infoChapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.infochapter', verbose_name='Раздел информации на wiki')),
            ],
            options={
                'verbose_name': 'Подраздел на сайте',
                'verbose_name_plural': 'Подразделы на сайте',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=300, verbose_name='Название статьи')),
                ('i_img', models.ImageField(blank=True, upload_to='info_images/', verbose_name='Картинка для статьи')),
                ('i_date_creation', models.DateField(default=datetime.date.today, verbose_name='Дата создания статьи')),
                ('i_text', models.TextField(verbose_name='Содержание статьи')),
                ('infoSubSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.infosubsection', verbose_name='Подраздел информации на wiki')),
            ],
            options={
                'verbose_name': 'Статья на сайте',
                'verbose_name_plural': 'Статьи на сайте',
            },
        ),
    ]
