# Generated by Django 4.2.14 on 2024-08-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wiki.info', verbose_name='Статья на wiki'),
            preserve_default=False,
        ),
    ]
