# Generated by Django 4.2.14 on 2024-08-15 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_logmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmaterials',
            name='ml_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 14, 1, 1, 200083), verbose_name='Дата'),
        ),
    ]
