# Generated by Django 4.2.14 on 2024-08-15 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_logmaterials_ml_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmaterials',
            name='ml_date_add',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
